poteShare/config/routes.rb
Rails.application.routes.draw do
  get 'room/new'
  get 'room/index'
  get 'room/posts'
  get 'room/search_room'
  get 'room/show'
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get '/',to:'room#index'
  get 'reserve/room'
  get 'reserve/comprete'
  get 'reserve/confirm'
  get 'reserve/room'
devise_scope :users do
  post'update_profile',to:'users/registrations#update_profile'
  patch 'update_profile',to:'users/registrations#update_profile'
end

post 'room/create'
 post 'reserve/confirm'
 post 'reserve/comprete'
 post 'reserve/back' 
  get 'reserve/reserved'


  get 'search' => 'room#search'
  get 'room/search'

  resources :reserve
  resources :room
   resources :users
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

poteShare/app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, ImageUploader
validates :title,:comment,:area,:price,:image,presence: true
 
 
 def self.search(search)
    if search
      Room.where(['name LIKE ?', "%#{search}%"])
    else
      Room.all
    end
  end

end

poteShare/app/controllers/room_controller.rb
class RoomController < ApplicationController
    
    protect_from_forgery
    
  def index
   @q = Room.ransack(params[:q])
   @search = @q.result(distinct: true)
   

  end
  
  def show
    @user = current_user
  end
  
  def search_room
@q = Room.ransack(params[:q])
   @search = @q.result(distinct: true)
   @count = @search.count

  end
      
  def new
     @room = Room.new
    
  end
  
  def create
      @room = Room.new(room_params)
      
       if @room.save
         
         redirect_to  reserve_room_path(@room)
         
       else if @room.invalid?
           render :new
       end
  end
  end
  
  
  
  def room_params
        params.require(:room).permit(:title ,:price,:area,:comment,:image)
       
  end
  
  def posts
      @room =Room.all
  end
end

poteShare/app/helpers/room_helper.rb
module RoomHelper
end

poteShare/app/views/room/index.html.erb
<div class='post index'>
   <div class="notifications">
    </div>
    <div class="top">
    <div class="top-main">
        <div class="container">
            <div class="row col-lg-6">
                <div class="form-fream">
                    <div class="form-area">
                        
                        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
                 
                         <div class="search-form">
                            <p>エリア</p>
                         <%= search_form_for @q ,url: room_search_room_path do |f| %>
                         <%= f.search_field :area_cont,class: "index-search" , placeholder: "東京"%>
                         <%= f.submit "探す",class: "index-submit" %>
                         <% end %>
                        </div>   
                                       
                    </div>



                </div>
            </div>
        </div>
    </div>
    
    <div class="container">
        <div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row">
                <div class="panel-item col-lg-3 col-6">
                    
                    <span>東京</span>
                    <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg",width: "240px",height: "140px" ,class:"panel-image" ),room_search_room_path(q: {area_cont: "東京"})%>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>大阪</span>
                    <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg",width: "240px",height: "140px" ,class:"panel-image" ),room_search_room_path(q: {area_cont: "大阪"})%>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>京都</span>
                    <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg/",width: "240px",height: "140px" ,class:"panel-image shadow" ),room_search_room_path(q: {area_cont: "京都"})%>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>札幌</span>
                   <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg",width: "240px",height: "140px" ,class:"panel-image" ),room_search_room_path(q: {area_cont: "札幌"})%>
                    <div class="shadow"></div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>

poteShare/app/views/room/new.html.erb
 <div class="container-fiuld room-new">
    <div class="row">
       
<div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
    <ul>
    <li class="active"><%= link_to "基本情報",new_room_path %></a></li>
    </ul>
</div>


      
     <div class="col-lg-10 room-view">
            <div class="room-view-box">
                 <%= form_with class: "new_room", url: 'create',model: @room,local: true do |f| %>　 
                    <div class="update-content">
                        <div class="row">
                            <h5>ルーム情報登録</h5>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row ">
                          
          <%= f.label :title1 ,"ルーム名",class: "col-md-3 required-a" %>
          <%= f.text_field :title ,placeholder: "ルーム名を入力",class: "form-control mb-4 col-md-9"%>
              </div>
                    </div>
        
       <div class="update-content tarea-comment">
                        <div class="row ">
        <%= f.label :comment1 ,"ルーム紹介" ,class: "col-md-3 required-a"%>
       <%= f.text_area :comment,placeholder: "ルーム説明を入力",class: "form-control mb-4 col-md-9",:size=>"60x10"%>
         </div>
                    </div>
        
        <div class="update-content">
                        <div class="row">
          <%= f.label :price1 ,"料金" ,class: "col-md-3 required-a"%>
          <%= f.number_field :price,placeholder: "1日あたりの料金を入力",class: "form-control mb-4 col-md-9"%>
          </div>
                    </div>
 
        <div class="update-content">
                        <div class="row">
          <%= f.label :area1 ,"住所",class: "col-md-3 required-a" %>
          <%= f.text_field :area,placeholder: "住所を入力",class: "form-control mb-4 col-md-9"%>
        </div>
                    </div>
       <div class="update-content">
                        <div class="row">
          <%= f.label :image1,"ルーム画像",class: "col-md-3 required-a" %>
          <%= f.file_field :image ,class: " mb-4 col-md-9"%>
          </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
          <%= f.submit "登録",class: "submit"%>
            </div>
                    </div>
                    </div>
     </div>

             <%end%>
 </div>
 </div>                
                           
                  

poteShare/app/views/room/posts.html.erb
<div class = 'posts'><h5>登録済みルーム一覧</h5>
  
  
    <div class='posts-border'>
       
             <div class ='image ppd'>ルーム画像</div>
            <div class = 'title ppd'>ルーム名</div>
            <div class ='room ppd'>ルーム紹介</div>
            <div class ='price ppd'>料金	</div>
            <div class = 'day ppd'>作成日	</div>
            
            </div>
            
            <% @room.each do |room| %>
              
         <div class='posts-border'>
       
             <div class = 'posts-image'><% if room.image.url%>
              <%= link_to image_tag(room.image.url ,width: "240px",height: "140px" ),reserve_room_path(room)%>
            <%else%>
            <p>画像がありません</p>
          <%end%></div>
          <%= link_to room.title,reserve_room_path(room),class:'title2 ppd2'%>
            
            <div class ='room2 ppd2'><%= room.comment %></div>
            <div class ='price2 ppd2'>¥<%= room.price%>	</div>
            <div class = 'day2 ppd2'><%= room.updated_at.strftime("%Y年%m月%d日%-H時%M分")%>	</div>
            
            </div>
           
          
           
           <% end %>
           
   </table>
   <div class='posts-border'> </div>
</div>

poteShare/app/views/room/search_room.html.erb
  <div class='search_room'>
  <div class="row">
  <% @search.each do |room| %>
  
   <div class="room-frame-inner">
    <%= link_to reserve_room_path(room) do %>
          <div class="room-image-out">
            <% if room.image.url%>
              <%= image_tag room.image.url ,width: "330px",height: "180px" %>
            <%else%>
             <p>画像がありません</p>
            <%end%>
          </div>
          <div class = 'down'>
            <p class = 'search-title'><%= room.title %></p>
            <p class = 'search-area'><%= room.area %></p>
            <p class = 'search-price'>¥<%= room.price%></p>
          </div>
    <% end %>
   </div>  
  <% end%>
 </div>
</div>

</div>

poteShare/app/views/room/show.html.erb
  <div class="container-fiuld user">
    <div class="row">
        
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
     <ul>
        <li class="active"><%= link_to "アカウント",room_show_path %></a></li>
        <li class="no-active"><%= link_to "プロフィール",users_show_path %></a></li>
    </ul>
</div>
        <div class="col-md-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>アカウント</h5>
                    </div>
                </div>
       
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="email">メールアドレス</label>
                        <div class="col-md-9"><%= @user.email %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="password">パスワード</label>
                        <div class="col-md-9">********</div></div>
                    </div>
                
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="password"><%= link_to "編集",edit_user_registration_path, class:"col-md-2 btn btn-primary mx-3"%></label>
                      <div class="col-md-9"> </div> 
                    </div>
                </div>
            </div>
     
            </div>
        </div>
    </div>
</div>